# Generated by Django 2.2 on 2019-04-18 17:15

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('target_currency', djmoney.models.fields.CurrencyField(default='EUR', max_length=3)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='rate')),
                ('uploaded', models.DateTimeField(verbose_name='uploaded')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
            },
        ),
    ]
